apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: platform-config
    namespace: argocd
    options:
      disableNameSuffixHash: true
    files:
      - platform.yaml

patches:
  - target:
      kind: Application
      name: platform
    patch: |
      - op: replace
        path: /spec/source/repoURL
        value: https://github.com/gambol99/eks-tenant.git
