apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: argocd
  app.kubernetes.io/managed-by: argocd
  app.kubernetes.io/instance: argocd
  app.kubernetes.io/part-of: argocd
  app.kubernetes.io/type: helm
  phase: primary

commonAnnotations:
  platform.local/tenant: grn

resources:
  - bootstrap.yaml

patches:
  - target:
      kind: ApplicationSet
      name: bootstrap
    patch: |
      - op: replace
        path: /spec/generators/0/git/repoURL
        value: https://github.com/gambol99/eks-tenant.git
