---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
  namespace: argocd
spec:
  ## The project to use for the application
  project: default

  ## The source to use for the application
  source:
    repoURL: https://github.com/gambol99/eks-platform.git
    targetRevision: HEAD
    path: overlays/release

  ## The destination to deploy the resources
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  ## The sync policy to use for the application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
