---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
  namespace: argocd
spec:
  ## The project to use for the application
  project: default
  ## The source is patched in the overlay
  source:
    repoURL: PLATFORM_REPO
    targetRevision: HEAD
    path: kustomize/overlays/release
    ##
    # We push the patches into the overlay, so we don't need allowing
    # for the git reference to trickle down into the platform.
    #
    #    patches:
    #      - target:
    #          kind: Application
    #          name: sync-platform
    #        patch: |
    #          - op: replace
    #            path: /spec/generators/0/git/repoURL
    #            value: https://github.com/gambol99/eks-tenant.git
    #          - op: replace
    #            path: /spec/generators/0/git/files/0/path
    #            value: clusters/grn.yaml
    kustomize: {}

  ## The destination to deploy the resources
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  ## The sync policy to use for the application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 20s
        maxDuration: 5m
    syncOptions:
      - AutoSync.allowEmpty=true
      - CreateNamespace=false
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
